## NOTE: not all parameters below are required - the Simulation class and all Object classes have many default parameters

name: "Heat Conduction"  # name of the simulation
description: "Example simulation" # description of the simulation

visualization: "VTK" # what graphics to use ('Easy3D' for Easy3D graphics or 'None' for no graphics)

g-accel: 0 # downward acceleration due to gravity (in the z-direction) [m/s2]

input-device: "Mouse" # the input device for interactivity - "Mouse" or "Haptic" (Phantom Omni)

## different simulation "modes"
# sim-mode: "Frame-by-frame"  # "Frame-by-frame" lets you advance the simulation one frame at a time by pressing any key
sim-mode: "Visualization"     # "Visualization" runs the simulation at 'real-time' such that sim time = wall clock time
# sim-mode: "AFAP"            # "AFAP" runs the simulation As Fast As Possible, without caring if sim time is going faster than wall clock time

time-step: 1e-3   # simulation time step [s]
collision-rate: 1000 # rate at which to run collision detection [Hz] 
fps: 30 # frames per second of the visualization (i.e. how often to redraw graphics)
end-time: 100 # end time of the simulation [s]

## define elastic materials
materials:
  -
    name: "Soft Tissue 1"
    density: 1000   # density [kg/m^3]
    E: 2e4    # Young's modulus [Pa]
    nu: 0.45  # Poisson's ratio [-]
    mu-s: 0.0 # coefficient of static friction [-]
    mu-k: 0.0 # coefficient of kinetic friction [-]
    specific-heat: 3600   # specific heat capacity [J/kg * K]
    thermal-conductivity: 0.3 # thermal conductivity [W/m-K]
    electrical-conductivity: 0.5 # electrical conductivity [S/m]
    convective-heat-transfer-coeff: 0  # convection heat transfer coefficient between material and static air

# rendering settings
exposure: 0.2
hdr-image-filename: "../resource/rendering/hdr/surgery_1k.hdr"
create-skybox: true
# window-width: 1000
# window-height: 1000

## objects in the simulation
objects:

  ## example deformable object
  -
    name: "Cube1"

    ## type of object
    type: "FirstOrderXPBDMeshObject"  # use the 1st-order XPBD method
    # type: "XPBDMeshObject"          # use the standard, 2nd-order XPBD method

    ## filename to load from (.msh is GMSH's volumetric mesh format, but if .obj or .stl is provided, will automatically turn surface mesh to volume mesh)
    # filename: "../resource/general/stanford_bunny_lowpoly.msh"
    # filename: "../resource/cube/cube8.msh"
    # filename: "../resource/general/single.msh"
    filename: "../resource/cube/cube2.msh"
    # filename: "../resource/cube/cube8.msh"
    # filename: "../resource/cube/cube16.msh"
    # filename: "../resource/cube/cube32.msh"
    # filename: "../resource/tissue/Prostate.msh"
    # filename: "../resource/tissue/Trachea_processed.stl"
    # filename: "../resource/tissue/tracheal_tumor.msh"

    materials: ["Soft Tissue 1"] # the elastic material (must match with the name of a material defined above)

    ## visualization options
    render-type: "PBR"
    metallic: 0.0
    roughness: 0.3
    smooth-normals: false
    draw-points: false
    draw-edges: true
    draw-faces: true

    ## initial configuration
    max-size: 0.01   # size of largest model dimension (preserves aspect ratio)
    # size: [1, 1, 1]   # specify size of each dimension
    position: [0, 0.025, 0]   # initial position of mesh center of mass [m]
    velocity: [0, 0, 0.0]   # initial velocity [m/s] (applied to all vertices in the deformable mesh)
    rotation: [0, 0, 0]     # initial rotation [deg] (specified as XYZ Euler angles)

    ## collisions
    collisions: true

    ## XPBD-specific options
    num-solver-iters: 1   # number of solver loop iterations per time step 
    
    solver-type: "Gauss-Seidel"   # use Gauss-Seidel solver (i.e. update mesh after every constraint projection)
    # solver-type: "Jacobi"       # use Jacobi solver (i.e. update mesh only after going through every constraint projection)
    # solver-type: "Parallel-Jacobi"  # use parallelized Jacobi solver (note: unstable and requires GPU)

    constraint-type: "Stable-Neohookean-Combined"   # use Stable Neohookean constraints with 2x2 block constraint solve for each tet element
    # constraint-type: "Stable-Neohookean"          # use Stable Neohookean constraints with separate constraint solve for each tet element

    # residual-policy: "Every-Substep"    # compute the residuals after every time step
    residual-policy: "Never"              # don't compute the residuals

    ## 1st-Order XPBD options (has no effect on XPBDMeshObject)
    damping-multiplier: 2e5   # 'b' from the 1st-Order XPBD paper
    adjust-damping-to-material: true

    compute-heat-conduction: true


  -
    name: "Robot"
    type: "VirtuosoRobot"
    # position: [0, -0.035, -0.0015] #"close position"
    position: [0, 0, 0]
    rotation: [-90, 180, 0]
    collisions: true
    # rendering settings
    color: [0.7, 0.7, 0.7]
    render-type: "PBR"
    metallic: 1.0
    roughness: 0.2

    arms:
    -
      name: "Arm1"
      type: "VirtuosoArm"
      tool-type: "cautery"
      tool-tube-length: 5e-3
      outer-tube-diameter: 1.56e-3
      outer-tube-radius-of-curvature: 1.5383e-2
      outer-tube-distal-straight-length: 5e-3
      outer-tube-translation: 6e-3
      outer-tube-rotation: 1030
      inner-tube-rotation: 30
      inner-tube-diameter: 1.04e-3
      inner-tube-translation: 10e-3