name: "Virtuoso Trachea"
visualization: "VTK"

# Tissue grasping simulation-specific parameters
input-device: "Mouse" # the input device for interactivity - "Mouse" or "Haptic" (Phantom Omni)
# fixed-faces-filename: "../resource/demos/trachea_virtuoso/cao_04_29_25_model1_decimated3_r_fixed_faces.txt"
# tumor-faces-filename: "../resource/demos/trachea_virtuoso/cao_04_29_25_model1_decimated3_r_tumor_faces.txt"
show-tip-cursor: true
# fixed-faces-filename: "../resource/demos/trachea_virtuoso/trachea_fixed_faces.txt"
# tumor-faces-filename: "../resource/demos/trachea_virtuoso/tumor_faces.txt"
# goal-filename: "../resource/demos/trachea_virtuoso/goals/goal1.obj"
# goals-folder: "../resource/demos/trachea_virtuoso/goals/"

# fixed-faces-filename: "../resource/demos/trachea_virtuoso/tracheal_tumor_v2_refined_fixed_faces.txt"
# tumor-faces-filename: "../resource/demos/trachea_virtuoso/tracheal_tumor_v2_refined_tumor_faces.txt"

# haptic-device-name1: "LeftOmni"
# haptic-device-name2: "RightOmni"
haptic-force-scaling: 0.0
# device-name1: "Omni"

g-accel: 9.81 # m/s2
# sim-mode: "Visualization"
# sim-mode: "Frame-by-frame"
sim-mode: "AFAP"
time-step: 3.33e-3 # for FO XPBD
# time-step: 3.33e-5 # for normal XPBD
collision-rate: 100
fps: 30
end-time: 5000

express-meshes-in-vb-frame: true

materials:
  -
    name: "Raw Chicken Breast"
    label: "Tumor"
    # material parameters
    density: 1060
    E: 0.07e6
    nu: 0.49

    # rendering settings
    color: [1.0, 0.4, 0.3]
    render-type: "PBR"
    metallic: 0.0
    roughness: 0.3
    smooth-normals: false
    draw-points: false
    draw-edges: true
    draw-faces: true

  -
    name: "Nitinol"
    # rendering settings
    color: [0.7, 0.7, 0.7]
    render-type: "PBR"
    metallic: 1.0
    roughness: 0.2

# rendering settings
exposure: 0.2
hdr-image-filename: "../resource/rendering/hdr/surgery_1k.hdr"
create-skybox: true
window-width: 800
window-height: 800

objects:

  -
    name: "Prostate"
    # type: "XPBDMeshObject"
    type: "FirstOrderXPBDMeshObject"
    # filename: "../resource/demos/prostate/bph_r.msh"
    filename: "../resource/demos/prostate/01_15_26/bph_model2_processed.msh"
    fixed-faces-filename: "../resource/demos/prostate/01_15_26/bph_model2_processed_fixed_faces.txt"
    materials: ["Raw Chicken Breast"]
    scaling: [1e-3, 1e-3, 1e-3]
    position: [0.10, 0.11, 0.14]
    velocity: [0, 0, 0]
    rotation: [30, 0, 0]
    num-solver-iters: 1
    num-local-collision-iters: 3
    residual-policy: "Never"
    solver-type: "Gauss-Seidel"
    # solver-type: "Jacobi"
    # solver-type: "Parallel-Jacobi"
    constraint-type: "Stable-Neohookean-Combined"
    damping-multiplier: 1e5
    adjust-damping-to-material: true
    # damping-multiplier: 40000000000
    collisions: true
    self-collisions: false

    # rendering settings
    colors: [[1.0, 0.3, 0.2]]
    render-type: "PBR"
    metallic: 0.0
    roughness: 0.3
    smooth-normals: true
    draw-points: false
    draw-edges: false
    draw-faces: true

  -
    name: "Robot"
    type: "VirtuosoRobot"
    material: "Nitinol"
    position: [0.002, 0, 0.016]
    rotation: [0, 180, 0]
    collisions: true

    arms:
    -
      name: "Arm1"
      type: "VirtuosoArm"
      tool-type: "none"
      tool-tube-length: 3e-3
      outer-tube-diameter: 1.56e-3
      outer-tube-radius-of-curvature: 1.5383e-2
      outer-tube-distal-straight-length: 5e-3
      outer-tube-translation: 6e-3
      outer-tube-rotation: 1030
      inner-tube-rotation: 30
      inner-tube-diameter: 1.04e-3
      inner-tube-translation: 15e-3

    -
      name: "Arm2"
      type: "VirtuosoArm"
      tool-type: "none"
      outer-tube-diameter: 1.56e-3
      outer-tube-radius-of-curvature: 1.5383e-2
      outer-tube-distal-straight-length: 5e-3
      outer-tube-translation: 6e-3
      outer-tube-rotation: 0
      inner-tube-rotation: 0
      inner-tube-diameter: 1.04e-3
      inner-tube-translation: 10e-3

  


